import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "../styles/main.scss";

const geologica = Geologica({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geologica.variable}>{children}</body>
    </html>
  );
}
