name: main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-main
  cancel-in-progress: true
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: find last sucessfull build commit
        uses: nrwl/nx-set-shas@v3

        # Setting BASE_COMMIT to:
        #  - on "main" run only for packages which changed since last successful build
        #  - on other branches run for all packages which changed compared to current origin/main (default option in package.json)
      - name: Set BASE_COMMIT
        if: github.ref_name == 'main'
        run: echo "BASE_COMMIT=[${{ env.NX_BASE }}]" >> $GITHUB_ENV
      - run: 'echo "BASE_COMMIT: $BASE_COMMIT"'

      - run: pnpm install
      - run: pnpm build:affected
      - run: pnpm lint:affected
      - run: pnpm test:affected
      - run: pnpm deploy:affected
